In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2


In [3]:
train=pd.read_csv("./train.csv", index_col=False)
test=pd.read_csv("./test.csv", index_col=False)


In [4]:
def ratio_cal(dx,dy,size):
    area = (dx*dy)/size
    x = int(np.sqrt(area*(dx/dy)).round())
    y = int(((dy/dx)*x).round())
    return x,y

In [5]:
def make_points(array):
    x1 = array[5]
    y1 = array[6]
    x2 = array[7]
    y2 = array[8]
    dx = np.abs(x2-x1)
    dy = np.abs(y2-y1)
    image = str(array[0])
    return x1,y1,x2,y2,dx,dy,image

In [18]:
train.values[0]

array([3404444, 'plastic', 1, 2268, 4032, 778, 1572, 1433, 2255, 4.89,
       157, 151, 143], dtype=object)

In [20]:
imagePath = "F:/reusable-trash-images/selectstar-reusable-trash-image/"
x1,y1,x2,y2,dx,dy,image = make_points(train.values[0])
path = imagePath + image +".jpg"
dx2, dy2 =ratio_cal(dx,dy,0.25)
delta_x =int((dx2-dx)/2)
delta_y =int((dy2-dy)/2)
pt1_x = x1-delta_x
pt1_y = y1-delta_y
pt2_x = x2+delta_x
pt2_y = y2+delta_y

img = cv2.imread(path, cv2.IMREAD_COLOR)
roi = img[pt1_y:pt2_y,pt1_x:pt2_x]
print("자른 이미지 높이",roi.shape[0])
print("자른 이미지 너비",roi.shape[1])
print(pt1_x, pt1_y)
print(pt2_x, pt2_y)
print(x1-pt1_x, y1-pt1_y)
print(x1-pt1_x+(x2-x1), y1-pt1_y+(y2-y1))

자른 이미지 높이 1365
자른 이미지 너비 1309
451 1231
1760 2596
327 341
982 1024


In [25]:
train.values[0]

array([3404444, 'plastic', 1, 2268, 4032, 778, 1572, 1433, 2255, 4.89,
       157, 151, 143], dtype=object)

In [26]:
dict = {
    "version": "4.5.10",
    "flags": {},
    "shapes": [
        {
            "label": train.values[i][1],
            "points": [
                [
                    x1-pt1_x,
                    y1-pt1_y
                ],
                [
                    x1-pt1_x+(x2-x1),
                    y1-pt1_y+(y2-y1)
                ]
            ],
            "group_id": "null",
            "shape_type": "rectangle",
            "flags": {}
        }
    ],
    "imagePath": f"{image}-85.jpg",
    "imageData": "null",
    "imageHeight": roi.shape[0],
    "imageWidth": roi.shape[1]
}


NameError: name 'i' is not defined

In [24]:
import json
with open(f"./data_85/{}-85.json", 'w') as f:
    json.dump(dict,f,indent=4)

In [47]:
imagePath = "F:/reusable-trash-images/selectstar-reusable-trash-image/"
error_file = []
for i in range(len(test.values)):
    try:
        x1,y1,x2,y2,dx,dy,image = make_points(test.values[i])
        dx2, dy2 =ratio_cal(dx,dy,0.75)
        delta_x =int((dx2-dx)/2)
        delta_y =int((dy2-dy)/2)
        pt1_x = x1-delta_x
        pt1_y = y1-delta_y
        pt2_x = x2+delta_x
        pt2_y = y2+delta_y
        if pt1_x <0:
            pt1_x = x1-int(delta_x/2)
            pt2_x = x2+int(delta_x/2)
        if pt1_y <0:
            pt1_y = y1-int(delta_y/2)
            pt2_y = y2+int(delta_y/2)
        path = imagePath + image +".jpg"
        img = cv2.imread(path, cv2.IMREAD_COLOR)
        roi = img[pt1_y:pt2_y,pt1_x:pt2_x]
        print((dx*dy)/(roi.shape[0]*roi.shape[1]))
        if ((dx*dy)/(roi.shape[0]*roi.shape[1])>=1):
            error_file.append(image)
        else:
            cv2.imwrite(f"./test/images/{image}-25.jpg", roi)
            dict = {
                "version": "4.5.10",
                "flags": {},
                "shapes": [
                            {
                                "label": test.values[i][1],
                                "points": [
                                            [
                                                x1-pt1_x,
                                                y1-pt1_y
                                            ],
                                            [
                                                    x1-pt1_x+(x2-x1),
                                                    y1-pt1_y+(y2-y1)
                                            ]
                                ],
                                "group_id": "null",
                                "shape_type": "rectangle",
                                "flags": {}
                                }
                            ],
                "imagePath": f"{image}-25.jpg",
                "imageData": "null",
                "imageHeight": roi.shape[0],
                "imageWidth": roi.shape[1]
            }
            with open(f"./test/labels/{image}-25.json", 'w') as f:
                json.dump(dict,f,indent=4)
    except:
        error_file.append(image)


0.753875012743399
0.7498543972044264
0.7549035218505277
0.7522012578616353
0.7536989007817732
0.7518814548720252
0.7522188346883469
0.7526217908980142
0.7539777310148115
0.750309405940594
0.7505582137161084
0.752129221732746
0.7521389241846675
0.7491872803181571
0.7511197663096397
0.7508103382920621
0.7519976594436885
0.7525864880087748
0.7511623167360872
0.752146256968603
0.7502557442085626
0.7508265203807677
0.7514669977050247
0.751580757752036
0.7504129442480862
0.751538046411225
0.7511261543305509
0.7503877499867079
0.7515900310358269
0.7523092077140857
0.750975800156128
0.7515151515151515
0.7505582137161084
0.7501571853720435
0.7504191616766467
0.7533579910453572
0.7514191952968257
0.750140056022409
0.7516150158986284
0.7517714285714285
0.749694472383548
0.7521452555652282
0.752464616886286
0.7519894491809422
0.751980836557951
0.7518477157768718
0.7516872890888638
0.7507598784194529
0.7496298667520307
0.7498300647012915
0.7500994645962874
0.7515837477559274
0.7521244328578949
0.75

In [41]:
train.values[0]

array([3404444, 'plastic', 1, 2268, 4032, 778, 1572, 1433, 2255, 4.89,
       157, 151, 143], dtype=object)

In [48]:
imagePath = "F:/reusable-trash-images/selectstar-reusable-trash-image/"
error_file = []
for i in range(len(train.values)):
    try:
        x1,y1,x2,y2,dx,dy,image = make_points(train.values[i])
        path = imagePath + image +".jpg"
        img = cv2.imread(path, cv2.IMREAD_COLOR)
        cv2.imwrite(f"./test/images/{image}-100.jpg", img)
        dict = {
            "version": "4.5.10",
            "flags": {},
            "shapes": [
                        {
                            "label": train.values[i][1],
                            "points": [
                                        [
                                            x1,
                                            y1
                                        ],
                                        [
                                            x2,
                                            y2
                                        ]
                            ],
                            "group_id": "null",
                            "shape_type": "rectangle",
                            "flags": {}
                            }
                        ],
            "imagePath": f"{image}-100.jpg",
            "imageData": "null",
            "imageHeight": test.values[i][4],
            "imageWidth": test.values[i][3]
        }
        with open(f"./test/labels/{image}-100.json", 'w') as f:
            json.dump(dict,f,indent=4)
    except:
        error_file.append(image)
